name: Build & Deploy Engine

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    env:
      SDL_VERSION: 2.0.14
      GH_CPU_ARCH: x86
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANDROID_SDK_TOOLS_VER: 4333796
      UPLOADTOOL_ISPRERELEASE: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Checkout xash-extras
      uses: actions/checkout@v2
      with:
        repository: FWGS/xash-extras
        path: xash-extras

    - name: Dependencies
      run: bash scripts/gha/deps_win32.sh

    - name: Build
      run: |
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuild = & "$vswhere" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
        & $msbuild xash3d-fwgs.sln -property:Configuration=Release -property:Platform=Win32
        if (-not $?) { throw "Failed" }
      env:
          RTGL1_SDK_PATH: ${{ github.workspace }}\RTGL1

    - name: Prepare folder
      run: |
        mkdir -p final/rt_bin
        mkdir -p final/rt/valve/cl_dlls
        mkdir -p final/rt/valve/dlls
        mkdir -p final/valve
        copy Win32/Release/*.dll final/rt_bin
        copy Win32/Release/*.exe final/rt_bin
        echo "xash3d.exe -console" | Out-File -encoding ASCII final/rt_bin/xash3d-console.bat
        copy SDL2_VC/lib/x86/SDL2.dll final/rt_bin
        copy HLSDK/cl_dlls/*.dll final/rt/valve/cl_dlls
        copy HLSDK/dlls/*.dll final/rt/valve/dlls
        copy -r RTGL1/ovrd/* final/rt
        copy -r scripts/rt/* final/valve
        copy RTGL1/VERSION final/VERSION_RTGL1
        echo "${{ github.sha }}" | Out-File -encoding ASCII final/VERSION

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: hl1-rt
        path: final/*
